### ISSUE TITLE
typo fax text (can't find it in the repo)

### ISSUE THREAD

**Issue by PeterTheOne** [Netzfreiheit/SaveTheInternet#41]
typo fax text (can't find it in the repo):

"losers in th market" -> "losers in the market"

**Comment by socialhack** [comment]
this repo is her: https://github.com/Netzfreiheit/Contact-Your-MEP

**Comment by PeterTheOne** [comment]
thnx

https://github.com/Netzfreiheit/Contact-Your-MEP/pull/16
