### ISSUE TITLE
Call your MEP only seems to display French MEPs

### ISSUE THREAD

**Issue by dnivi3** [Netzfreiheit/SaveTheInternet#72]
So, I have been cycling through the MEPs on the site and I can only seem to get French MEPs to call. I remember a month ago or so I could choose the country or have it set to random.

I also checked on La Quadrante du Net's website and it seems the campaign is expired (?). However, their new [Net Neutrality campaign of Pi-Phone](https://piphone.lqdn.fr/campaign/call2/NetNeutrality_2015_2) is available and lets me select the country and cycle through the selected country's MEPs. 

It is really important that the website and the calling functionality works properly, especially this close to the vote. Is maybe the wrong version of Pi-Phone embedded?

**Comment by socialhack** [comment]
fixed with https://github.com/Netzfreiheit/SaveTheInternet/commit/1269095954be8b8374b9c41e5618e32f1a1f60e4
